# Site settings
title: Aseem Baranwal
general_email: aseemrb@gmail.com
academic_email: aseem.baranwal@uwaterloo.ca

description: CS grad student @Uwaterloo.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://aseemrb.github.io" # the base hostname & protocol for your site

footer-links:
  email:
  scholar: DPt626YAAAAJ
  linkedin: aseemrb
  github: aseemrb
  telegram: aseemrb
  lastfm:
  rss: aseemrb
  keybase: aseemrb
  facebook:
  twitter:
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
