# Site settings
title: Aseem Baranwal
general_email: aseemrb@gmail.com
academic_email: aseem.baranwal@uwaterloo.ca

description: Aseem Raj Baranwal - CS grad student @Uwaterloo.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://aseemrb.me" # the base hostname & protocol for your site

footer-links:
  email:
  facebook:
  github: aseemrb
  keeweb: aseemrb
  keybase: aseemrb
  lastfm:
  linkedin: aseemrb
  rss: aseemrb
  scholar: DPt626YAAAAJ
  telegram: aseemrb
  twitter:

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
