# Site settings
title: Aseem Baranwal
general_email: aseemrb@gmail.com
academic_email: aseem.baranwal@uwaterloo.ca

description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://aseemrb.github.io" # the base hostname & protocol for your site

footer-links:
  email: aseemrb@gmail.com
  facebook:
  github: aseemrb
  lastfm: aseemraj
  linkedin: aseemrb
  rss: aseemrb
  twitter:
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
